# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 603)
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(550, 480, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("color: rgb(170, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.exit.setObjectName("exit")
        self.title1 = QtWidgets.QLabel(self.centralwidget)
        self.title1.setGeometry(QtCore.QRect(0, 10, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.title1.setFont(font)
        self.title1.setStyleSheet("color: rgb(0, 0, 127);")
        self.title1.setObjectName("title1")
        self.title2 = QtWidgets.QLabel(self.centralwidget)
        self.title2.setGeometry(QtCore.QRect(10, 40, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.title2.setFont(font)
        self.title2.setStyleSheet("color: rgb(0, 0, 127);")
        self.title2.setObjectName("title2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 50, 201, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Tabla_2_200x130.jpg"))
        self.label.setObjectName("label")
        self.status = QtWidgets.QTextEdit(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(470, 310, 201, 51))
        self.status.setObjectName("status")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 280, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(200, 14, 7)")
        self.label_4.setObjectName("label_4")
        self.per = QtWidgets.QPushButton(self.centralwidget)
        self.per.setGeometry(QtCore.QRect(240, 320, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setUnderline(False)
        self.per.setFont(font)
        self.per.setStyleSheet("color: rgb(170, 85, 255);")
        self.per.setObjectName("per")
        self.har = QtWidgets.QPushButton(self.centralwidget)
        self.har.setGeometry(QtCore.QRect(50, 320, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setUnderline(False)
        self.har.setFont(font)
        self.har.setStyleSheet("color: rgb(255, 85, 0);")
        self.har.setObjectName("har")
        self.hpss = QtWidgets.QPushButton(self.centralwidget)
        self.hpss.setGeometry(QtCore.QRect(240, 260, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setUnderline(False)
        self.hpss.setFont(font)
        self.hpss.setStyleSheet("color: rgb(255, 0, 0);")
        self.hpss.setObjectName("hpss")
        self.analyze = QtWidgets.QPushButton(self.centralwidget)
        self.analyze.setGeometry(QtCore.QRect(20, 480, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.analyze.setFont(font)
        self.analyze.setStyleSheet("color: rgb(85, 0, 127);")
        self.analyze.setObjectName("analyze")
        self.optaala = QtWidgets.QTextEdit(self.centralwidget)
        self.optaala.setGeometry(QtCore.QRect(220, 430, 231, 41))
        self.optaala.setObjectName("optaala")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(50, 260, 161, 41))
        self.spinBox.setObjectName("spinBox")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 100, 391, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.start = QtWidgets.QPushButton(self.frame)
        self.start.setGeometry(QtCore.QRect(10, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.start.setFont(font)
        self.start.setAutoFillBackground(True)
        self.start.setStyleSheet("color: rgb(0, 150, 0);\n"
"gridline-color: rgb(255, 170, 0);\n"
"")
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.frame)
        self.stop.setGeometry(QtCore.QRect(200, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.stop.setFont(font)
        self.stop.setStyleSheet("color: rgb(150, 0, 0);\n"
"\n"
"")
        self.stop.setObjectName("stop")
        self.recordlabel = QtWidgets.QLabel(self.frame)
        self.recordlabel.setGeometry(QtCore.QRect(20, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.recordlabel.setFont(font)
        self.recordlabel.setObjectName("recordlabel")
        self.frame.raise_()
        self.exit.raise_()
        self.title1.raise_()
        self.title2.raise_()
        self.label.raise_()
        self.status.raise_()
        self.label_4.raise_()
        self.per.raise_()
        self.har.raise_()
        self.hpss.raise_()
        self.analyze.raise_()
        self.optaala.raise_()
        self.label_5.raise_()
        self.spinBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AD&C"))
        self.exit.setText(_translate("MainWindow", "Quit"))
        self.title1.setText(_translate("MainWindow", " Automatic Detection and Classification of Tabla"))
        self.title2.setText(_translate("MainWindow", " taalas from Indian Classical Music "))
        self.label_4.setText(_translate("MainWindow", "Status :-"))
        self.per.setText(_translate("MainWindow", "Play Percussive"))
        self.har.setText(_translate("MainWindow", "Play Harmonic "))
        self.hpss.setText(_translate("MainWindow", "Separate"))
        self.analyze.setText(_translate("MainWindow", "Analyze"))
        self.label_5.setText(_translate("MainWindow", "Classified Tabla taal :-"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.recordlabel.setText(_translate("MainWindow", "Recording"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

