# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 603)
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(480, 440, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("color: rgb(170, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.exit.setObjectName("exit")
        self.title1 = QtWidgets.QLabel(self.centralwidget)
        self.title1.setGeometry(QtCore.QRect(0, 10, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.title1.setFont(font)
        self.title1.setStyleSheet("color: rgb(0, 0, 127);")
        self.title1.setObjectName("title1")
        self.title2 = QtWidgets.QLabel(self.centralwidget)
        self.title2.setGeometry(QtCore.QRect(0, 40, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.title2.setFont(font)
        self.title2.setStyleSheet("color: rgb(0, 0, 127);")
        self.title2.setObjectName("title2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 80, 201, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Tabla_2_200x130.jpg"))
        self.label.setObjectName("label")
        self.status = QtWidgets.QTextEdit(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(470, 363, 201, 51))
        self.status.setObjectName("status")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 331, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(200, 14, 7)")
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 90, 421, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.start = QtWidgets.QPushButton(self.frame)
        self.start.setGeometry(QtCore.QRect(10, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.start.setFont(font)
        self.start.setAutoFillBackground(True)
        self.start.setStyleSheet("color: rgb(0, 150, 0);\n"
"gridline-color: rgb(255, 170, 0);\n"
"")
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.frame)
        self.stop.setGeometry(QtCore.QRect(200, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.stop.setFont(font)
        self.stop.setStyleSheet("color: rgb(150, 0, 0);\n"
"\n"
"")
        self.stop.setObjectName("stop")
        self.recordlabel = QtWidgets.QLabel(self.frame)
        self.recordlabel.setGeometry(QtCore.QRect(150, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.recordlabel.setFont(font)
        self.recordlabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.recordlabel.setObjectName("recordlabel")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 210, 421, 181))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.har = QtWidgets.QPushButton(self.frame_2)
        self.har.setGeometry(QtCore.QRect(230, 50, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setUnderline(False)
        self.har.setFont(font)
        self.har.setStyleSheet("color: rgb(255, 85, 0);")
        self.har.setObjectName("har")
        self.per = QtWidgets.QPushButton(self.frame_2)
        self.per.setGeometry(QtCore.QRect(230, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setUnderline(False)
        self.per.setFont(font)
        self.per.setStyleSheet("color: rgb(170, 85, 255);")
        self.per.setObjectName("per")
        self.hpss = QtWidgets.QPushButton(self.frame_2)
        self.hpss.setGeometry(QtCore.QRect(20, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setUnderline(False)
        self.hpss.setFont(font)
        self.hpss.setStyleSheet("color: rgb(255, 0, 0);")
        self.hpss.setObjectName("hpss")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(80, 10, 311, 17))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_2.setObjectName("label_2")
        self.margin_per = QtWidgets.QSpinBox(self.frame_2)
        self.margin_per.setGeometry(QtCore.QRect(20, 66, 60, 41))
        self.margin_per.setObjectName("margin_per")
        self.margin_har = QtWidgets.QSpinBox(self.frame_2)
        self.margin_har.setGeometry(QtCore.QRect(120, 66, 60, 41))
        self.margin_har.setObjectName("margin_har")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(21, 34, 67, 17))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 85, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(123, 34, 67, 17))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 170, 255);")
        self.label_8.setObjectName("label_8")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 410, 421, 131))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.optaala = QtWidgets.QTextEdit(self.frame_3)
        self.optaala.setGeometry(QtCore.QRect(180, 70, 231, 41))
        self.optaala.setObjectName("optaala")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 74, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_5.setObjectName("label_5")
        self.analyze = QtWidgets.QPushButton(self.frame_3)
        self.analyze.setGeometry(QtCore.QRect(10, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.analyze.setFont(font)
        self.analyze.setStyleSheet("color: rgb(85, 0, 127);")
        self.analyze.setObjectName("analyze")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(160, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(170, 85, 127);")
        self.label_3.setObjectName("label_3")
        self.marginvalue_har = QtWidgets.QTextEdit(self.centralwidget)
        self.marginvalue_har.setGeometry(QtCore.QRect(606, 234, 61, 41))
        self.marginvalue_har.setObjectName("marginvalue_har")
        self.text_margin = QtWidgets.QLabel(self.centralwidget)
        self.text_margin.setGeometry(QtCore.QRect(470, 244, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.text_margin.setFont(font)
        self.text_margin.setStyleSheet("color: rgb(255, 85, 127);")
        self.text_margin.setObjectName("text_margin")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(470, 290, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_6.setObjectName("label_6")
        self.marginvalue_per = QtWidgets.QTextBrowser(self.centralwidget)
        self.marginvalue_per.setGeometry(QtCore.QRect(606, 280, 61, 41))
        self.marginvalue_per.setObjectName("marginvalue_per")
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.frame.raise_()
        self.exit.raise_()
        self.title1.raise_()
        self.title2.raise_()
        self.label.raise_()
        self.status.raise_()
        self.label_4.raise_()
        self.marginvalue_har.raise_()
        self.text_margin.raise_()
        self.label_6.raise_()
        self.marginvalue_per.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AD&C"))
        self.exit.setText(_translate("MainWindow", "Quit"))
        self.title1.setText(_translate("MainWindow", " Automatic Detection and Classification of Tabla"))
        self.title2.setText(_translate("MainWindow", " taalas from Indian Classical Music "))
        self.label_4.setText(_translate("MainWindow", "Status :-"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.recordlabel.setText(_translate("MainWindow", "Recording"))
        self.har.setText(_translate("MainWindow", "Play Harmonic "))
        self.per.setText(_translate("MainWindow", "Play Percussive"))
        self.hpss.setText(_translate("MainWindow", "Separate"))
        self.label_2.setText(_translate("MainWindow", "Harmonic & Percussive Separation"))
        self.label_7.setText(_translate("MainWindow", "Per"))
        self.label_8.setText(_translate("MainWindow", "Har"))
        self.label_5.setText(_translate("MainWindow", "Classified Tabla taal :-"))
        self.analyze.setText(_translate("MainWindow", "Analyze"))
        self.label_3.setText(_translate("MainWindow", "Prediction"))
        self.text_margin.setText(_translate("MainWindow", "Margin @Har:-"))
        self.label_6.setText(_translate("MainWindow", "Margin @Per :-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

